# This file was generated by GoReleaser. DO NOT EDIT.
cask "webctl" do
  version "0.1.7"

  on_macos do
    on_arm do
      sha256 "b1194b3bd3ac0a3154654348482cbc4dd8eaf9693571f102e6cbab868f68e302"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c611d5b1774f9eea334d85092037acc3df768a6bdda8b765a8a37d8e444cf017"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9799a68e9bb76a163a2c6a7e23cf0c9169512fee1f989bde3f169a94e142a1dd"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c466e2148c6eab470e1574115d5e14ae8f1ea3a575a9465d65fc6a77aae9854"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "webctl"
  desc "Smart web search CLI for agents, backed by Jev. Saves a lot of tokens."
  homepage "https://github.com/dorkitude/webctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webctl"]
    end
  end

  # No zap stanza required
end
