# This file was generated by GoReleaser. DO NOT EDIT.
cask "webctl" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "432c87e38a13cc691853ba4f9a726684e36cf57b4281ddc16e32b767cc59bf79"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e362cb97d7511b924b745a72e4fb19075280b306e7d5d761cfa4d75777b5508a"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "647dc690d77d1c769fb4be8af3da46b9aedb8f37258614ace7484a3333d41dc1"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dec0505c3d748382c1874b85ffb190836723a831402d1b1cfa60a4f580ac4431"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "webctl"
  desc "Smart web search CLI for agents, backed by Jev. Saves a lot of tokens."
  homepage "https://github.com/dorkitude/webctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webctl"]
    end
  end

  # No zap stanza required
end
