# This file was generated by GoReleaser. DO NOT EDIT.
cask "webctl" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "41362b8c38f7706502afbe6a445c2deac485d55d352a2f660b47945950dfbecc"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "661c7d2798c1e2d38b994ed29c721aba85b06130a972ed88a99dbd3529822c4f"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "790f1d952a626fd9b9b7fb93d5b48e846f4e6c72adc63b71a70605199b426805"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "885237bea4b3176d0a3dc0ffe19563dce6d97d27b2911b448ecae87147c1819d"
      url "https://github.com/dorkitude/webctl/releases/download/v#{version}/webctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "webctl"
  desc "Smart web search CLI for agents, backed by Jev. Saves a lot of tokens."
  homepage "https://github.com/dorkitude/webctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webctl"]
    end
  end

  # No zap stanza required
end
